# This file was generated by GoReleaser. DO NOT EDIT.
cask "inodes" do
  name "inodes"
  desc "CLI for the Image Nodes image processing API"
  homepage "https://imagenodes.com"
  version "0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inodes"

  on_macos do
    on_intel do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_darwin_amd64.tar.gz"
      sha256 "ff19d814a6c9d0d5e90dfb17fc9fe97895b31112bc6c21dfbbb1c9f781d966dd"
    end
    on_arm do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_darwin_arm64.tar.gz"
      sha256 "39eb51763afb4bc3fdd3b2f130659c407d0d562404e8ac22f2351ce40924bb69"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_linux_amd64.tar.gz"
      sha256 "bcc20080bdb3362000bc57950428bb098d56cad4e946f4961b730974c3192ac9"
    end
    on_arm do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_linux_arm64.tar.gz"
      sha256 "7ed4325c8c0e1cde1c38b3ac4cc2505bfa57d9012441a30bfdd7fbd121d9f2fb"
    end
  end

  # No zap stanza required
end
