# This file was generated by GoReleaser. DO NOT EDIT.
cask "inodes" do
  name "inodes"
  desc "CLI for the Image Nodes image processing API"
  homepage "https://imagenodes.com"
  version "0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inodes"

  on_macos do
    on_intel do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_darwin_amd64.tar.gz"
      sha256 "4ed8570cfd0992d54d9f167ad006aeecaa79b390e4686312903cf2a13330ae3a"
    end
    on_arm do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_darwin_arm64.tar.gz"
      sha256 "ea2b7ec37b0c0f7698ee3886ed379e3829d9bd61d38d59e4e8ab686b822fe856"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_linux_amd64.tar.gz"
      sha256 "2f1861db8e20c99165b1989debebadb00a4d19967b2fdcfc347919525831fd42"
    end
    on_arm do
      url "https://github.com/dmt195/inodes-cli/releases/download/v#{version}/inodes_linux_arm64.tar.gz"
      sha256 "355d7905e8bc5723421e8f8599e314c6708b7125055ff63797826f2c61ff212e"
    end
  end

  # No zap stanza required
end
